logging.level.com.liferay=DEBUG

spring.datasource.url=jdbc:postgresql://localhost:5432/school-of-sorcery
spring.datasource.username=userdb
spring.datasource.password=passdb

spring.jpa.hibernate.ddl-auto=update

spring.sql.init.mode=never

spring.jackson.property-naming-strategy=SNAKE_CASE
